name: CI Day1

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run tests
        run: pytest -q --cov=./ --cov-report=term-missing --cov-fail-under=80
      - name: Bandit (security scan)
        run: bandit -q -r .
      - name: pip-audit (vuln scan)
        run: if [ -f requirements.txt ]; then pip-audit -r requirements.txt || true; fi
      - name: Generate SBOM
        run: pipdeptree --json-tree > sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
